#------------------
# HEATMAPS
#------------------
setwd("~/Dropbox/RAD_practice")

load("vsd.RData")
load("pvals.RData")
source("uniHeatmap.R")
# loading annotations - two-column tables
gg=read.table("amil_iso2gene.tab",sep="\t")  # gene names
gg=gg[-grep("Uncharacterized",gg$V2),]
kogs=read.table("amil_defog_iso2kogClass.tab",sep="\t")  # KOG classes
# loading GO annotations - lists of genes for each GO term (plus some additional info) - these files are generated by GOMWU.R script
gos.mf=read.table("GO_MWU-master/MF_heat_lpv.csv",sep="\t",header=T)
gos.cc=read.table("GO_MWU-master/CC_heat_lpv.csv",sep="\t",header=T)
#gos.bp=read.table("BP_heat_lpv.csv",sep="\t",header=T)
# loading WGCNA module kMEs 
upStress=read.csv("blue.csv")
downStress=read.csv("brown4.csv")

# reordering columns according to treatment
vsd=vsd[,order(a.con$trt)]
#--------------
# all genes passing a cutoff, for treatment

nums=uniHeatmap(vsd=vsd,gene.names=gg,
	metric=trt$padj, # metric of gene significance
	cutoff=1e-2, 
#	sort=c(1:ncol(vsd)),   # overrides sorting of columns according to hierarchical clustering
	cex=0.4,
	pdf=F,
	named=T
	)

#------------------------------
# by pattern in gene name 

pattern="[cC]arbonic anhydrase"

# how many genes we have with this pattern in gene name? 
sum(gg[grep(pattern,gg$V2),1] %in% row.names(vsd)) 

# plotting the ones that pass 0.01 pvalue cutoff:
nums=uniHeatmap(vsd=vsd,gene.names=gg,
	metric=trt$pvalue, # metric of gene significance
	cutoff=0.01, 
#	sort=c(1:ncol(vsd)),  # overrides sorting of columns according to hierarchical clustering
	pattern=pattern,  # pattern in gene name
	cex=1,  # font size
	pdf=FALSE  # change to TRUE to print to PDF
	)
nums # totalCutoffPassing, named, patternMatching 

#----------------
# top 5 percent significant genes (annotated only)

cutoff=0.01
metric=trt$pvalue
top5percent=ceiling(table(metric<0.05)[2]*cutoff)
tops=row.names(head(trt[order(metric),],top5percent))
nums=uniHeatmap(vsd=vsd[tops,],gene.names=gg,
	metric=trt[tops,]$pvalue,
	cutoff=cutoff,
#	sort=c(1:ncol(vsd)),  
	cex=0.8,
	pdf=FALSE
	)
nums # totalCutoffPassing, named, patternMatching 
#-------------------
# by pattern in KOG class name

kog.pattern="Inorganic"

isos=as.character(kogs$V1[grep(kog.pattern,kogs$V2)])
sevsd=vsd[row.names(vsd) %in% isos,]
sel.trt=trt[row.names(trt) %in% isos,]
quartz()
nums=uniHeatmap(vsd=sevsd,gene.names=gg,
	metric=sel.trt$pvalue,
	cutoff=0.1,
#	sort=c(1:ncol(vsd)),  
	sort=order(a.con$trt),
	cex=0.8,
	pdf=FALSE
	)

#--------------------
# by pattern in GO term

go.pattern="[Rr]ibosome"

goDiv=gos.cc 
goDiv[grep(go.pattern,goDiv$name),]
isos=as.character(goDiv$seq[grep(go.pattern,goDiv$name)])
sevsd=vsd[row.names(vsd) %in% isos,]
trt
sel.trt=trt[row.names(trt) %in% isos,]

nums=uniHeatmap(vsd=sevsd,gene.names=gg,
	metric=sel.trt$pvalue,
	cutoff=0.01,
#	sort=c(1:ncol(vsd)),  
	sort=order(a.con$trt),
	cex=0.8,
	pdf=FALSE
	)

#---------------------
# by WGCNA module membership (sorted from high to low)

module=upStress
cutoff=0.85 # module membership cutoff
signed=T

if (signed) { 
	inModule=module[abs(module[,2])>cutoff,] 
	} else {
		 inModule=module[module[,2]>cutoff,]
	}
genes=inModule[order(inModule[,2],decreasing=T),1]
genes=genes[genes %in% row.names(vsd)]
nums=uniHeatmap(vsd[genes,],gene.names=gg,
	metric=trt[genes,]$pvalue,
	cutoff=1,
	cluster_rows=F,
	sort=c(1:ncol(vsd)),  
	cex=0.8,	
	pdf=FALSE
	)
nums # totalCutoffPassing, named, patternMatching 


