#!/usr/bin/perl

my $usage= "

samcount_launch_bt2.pl:

Prints out list of commands to derive counts from SAM files
generated by bowtie2

prints to STOUT

Arguments:
1: glob to sam files
2: path-filename of clusters2isogroups table

Example:
samcount_launch_bt2.pl '\.sam' /path/to/reference/transcriptome_seq2iso.tab > sc

NOTE: for SAM files made by gmapper (SHRiMP), use samcount_launch.pl
			
";

if (!$ARGV[0]) { die $usage;}
my $glob=shift @ARGV or die $usage;
my $tab=shift @ARGV or die $usage;

opendir THIS, ".";
my @fqs=grep /$glob/,readdir THIS;
my $outname="";

foreach $fqf (@fqs) {
	$outname=$fqf.".counts";
	print "samcount.pl $fqf $tab >$outname\n";
}
